# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84d917d149d594ffba26fd1ae2976b30abc7a137cf3a1871fb779aae8dc1eb7f5772be63d9d7c67dea1a33dac4ddb76530cee806b9e44b2e6bef7cfb74f83ba2

test:
  secret_key_base: c8a16a733578a9268b0f995056be8457006790e996c5dd697fac75543b94f994eef1b9baa721ec13529cded1e42b2eaeef9694527db10da3e573d9108c4a6c53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
